apiVersion: v1
kind: Namespace
metadata:
  name: blue-green

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-blue
  namespace: blue-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ng
      env: blue
  template:
    metadata:
      labels:
        app: ng
        env: blue
    spec:
      containers:
      - name: ng-container
        image: zakir22/ng-18-app:v1
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-green
  namespace: blue-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ng
      env: green
  template:
    metadata:
      labels:
        app: ng
        env: green
    spec:
      containers:
      - name: ng-container
        image: zakir22/ng-18-app:v2
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ng-service
  namespace: blue-green
spec:
  type: LoadBalancer
  selector:
    app: ng
    env: green
  ports:
    - protocol: TCP
      port: 4300
      targetPort: 80