apiVersion: v1
kind: Namespace
metadata:
  name: rolling

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng
  namespace: rolling
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ng
  template:
    metadata:
      labels:
        app: ng
    spec:
      containers:
      - name: ng-container
        image: zakir22/ng-18-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ng-service
  namespace: rolling
spec:
  type: LoadBalancer
  selector:
    app: ng
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80