apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}-{{.Values.appV2}}
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.appName}}
      version: {{.Values.appV2}}
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
        version: {{.Values.appV2}}
    spec:
      containers:
      - name: {{.Values.appName}}-container
        image: {{.Values.image.repositoryV2}}
        ports:
        - containerPort: {{.Values.service.targetPort}}