namespace: "canary"
appName: "ng"
appV1: v1
appV2: v2
replicaCount: 3

image:
  repository: zakir22/ng-18-app:latest
  repositoryV1: zakir22/ng-18-app:v1
  repositoryV2: zakir22/ng-18-app:v2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  protocol: TCP
  port: 4400
  targetPort: 80
